# Generated by Django 5.2.4 on 2025-07-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='start_date',
            field=models.DateField(default='2025-07-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
